name: viyafaari_town
description: Viyafaari Town business application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_messaging: ^16.0.3
  supabase_flutter: 2.14.2
  image_picker: ^1.2.2
  geolocator: ^14.0.3
  url_launcher: ^6.3.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ehfassviyafaari_logo.png

  fonts:
    - family: Faruma
      fonts:
        - asset: assets/fonts/Faruma.ttf

    - family: Italianno
      fonts:
        - asset: assets/fonts/Italianno-Regular.ttf
