// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTf_eWdMqmRzkp-JmvLJZb5nyiSTrFO3k',
    appId: '1:266406107966:web:5c4bedb662b9c0304f2a6f',
    messagingSenderId: '266406107966',
    projectId: 'viyafaari-town',
    authDomain: 'viyafaari-town.firebaseapp.com',
    storageBucket: 'viyafaari-town.firebasestorage.app',
    measurementId: 'G-L99CZNWNN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_x4UfomcCu_vyo9avBE52N4m5ddEl-_Q',
    appId: '1:266406107966:android:8c3852606f24a5d04f2a6f',
    messagingSenderId: '266406107966',
    projectId: 'viyafaari-town',
    storageBucket: 'viyafaari-town.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm-O0E3hAp7c5jFfcQPE-9kjSfvFxjiok',
    appId: '1:266406107966:ios:4eed267a072553f34f2a6f',
    messagingSenderId: '266406107966',
    projectId: 'viyafaari-town',
    storageBucket: 'viyafaari-town.firebasestorage.app',
    iosClientId: '266406107966-cbjk8nnladk1kuc23q9t1snilu59q0e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.viyafaariTown',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm-O0E3hAp7c5jFfcQPE-9kjSfvFxjiok',
    appId: '1:266406107966:ios:4eed267a072553f34f2a6f',
    messagingSenderId: '266406107966',
    projectId: 'viyafaari-town',
    storageBucket: 'viyafaari-town.firebasestorage.app',
    iosClientId: '266406107966-cbjk8nnladk1kuc23q9t1snilu59q0e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.viyafaariTown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTf_eWdMqmRzkp-JmvLJZb5nyiSTrFO3k',
    appId: '1:266406107966:web:da9d13a451e3534e4f2a6f',
    messagingSenderId: '266406107966',
    projectId: 'viyafaari-town',
    authDomain: 'viyafaari-town.firebaseapp.com',
    storageBucket: 'viyafaari-town.firebasestorage.app',
    measurementId: 'G-LL1EYYRLEY',
  );
}
